apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: backend-secrets
  namespace: devops-project

spec:
  provider: gke

  parameters:
    secrets: |
      - resourceName: "projects/devops-gke-project-510307/secrets/backend-api-key/versions/1"
        path: "API_KEY"